export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

// single data
export const GET_SINGLE_DATA_REQUEST = 'GET_SINGLE_DATA_REQUEST';
export const GET_SINGLE_DATA_SUCCESS = 'GET_SINGLE_DATA_SUCCESS';
export const GET_SINGLE_DATA_FAILURE = 'GET_SINGLE_DATA_FAILURE';
